parameters:
    dir.vendor: 'vendor'
    rabbitmq.channel: 'randomnumber'
    email.admin: 'gt@kani.hu'
    db.dsn: 'mysql:dbname=%env(MYSQL_DATABASE)%;host=%env(MYSQL_HOST)%;port=%env(MYSQL_PORT)%'
    db.user: '%env(MYSQL_USER)%'
    db.password: '%env(MYSQL_PASSWORD)%'
