services:

    ##
    # Container configuration
    #

    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    ##
    # Console application
    #

    Symfony\Component\Console\Application:
        public: true


    ##
    # Database
    #

    PDO:
        class: PDO
        arguments:
            - '%db.dsn%'
            - '%db.user%'
            - '%db.password%'


    ##
    # Loggers
    #

    Symfony\Component\Console\Output\ConsoleOutput: ~

    logger.db:
        class: RandomQueue\Log\DatabaseLogger
        public: true
        arguments:
            $level: !php/const Psr\Log\LogLevel::DEBUG

    logger.console:
        class: Symfony\Component\Console\Logger\ConsoleLogger
        public: true
        arguments:
            $output: '@Symfony\Component\Console\Output\ConsoleOutput'

    # default logger
    logger: '@logger.db'

    # alias for autowiring
    Psr\Log\LoggerInterface: '@logger'


    ##
    # RabbitMQ
    #

    PhpAmqpLib\Connection\AbstractConnection: '@rabbitmq.connection'

    rabbitmq.connection:
        class: PhpAmqpLib\Connection\AMQPLazyConnection
        arguments:
            $host: '%rabbitmq.host%'
            $port: '%rabbitmq.port%'
            $user: '%rabbitmq.user%'
            $password: '%rabbitmq.password%'


    ##
    # Event dispatcher
    #

    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@event_dispatcher'

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher


    ##
    # Mail
    #

    mail.transport:
        class: Swift_SendmailTransport

    mailer:
        class: Swift_Mailer
        arguments:
            - '@mail.transport'


    ##
    # Application services
    #

    RandomQueue\:
        resource: '../src/*/*'

    RandomQueue\Routing\RouteRegistry:
        public: true

    RandomQueue\Queue\Worker:
        public: true
        arguments:
            $connection: '@rabbitmq.connection'
            $channelName: '%rabbitmq.channel%'

    RandomQueue\Queue\JobToMessageTransformer:
        public: true

    RandomQueue\Command\QueueConsumerCommand:
        tags:
            - { name: 'console.command', command: 'queue:consumer' }


    RandomQueue\Command\QueueJobAddCommand:
        tags:
            - { name: 'console.command', command: 'queue:job:add' }

    RandomQueue\EventSubscriber\JobSubscriber:
        arguments:
            $mailer: '@mailer'
            $notifyEmail: '%email.admin%'
        tags:
            - { name: 'kernel.event_subscriber' }
